caves = [
    {"id": 1, "name": "Lobos - Superfice 1 - Panuk"},
    {"id": 2, "name": "Lobos/Cave 1 - -1 - Panuk"},
    {"id": 3, "name": "Lobos/Cave 1 - -2 - Panuk"},
    {"id": 4, "name": "Lobos/Cave 1 - -3 - Panuk"},
    {"id": 5, "name": "Lobos/Cave 2 - -1 - Panuk"},
    {"id": 6, "name": "Lobos/Cave 2 - -2 - Panuk"},
    {"id": 7, "name": "Lobos/Cave 2 - -3 - Panuk"},
    {"id": 8, "name": "Lobos/Cave 3 - -1 - Panuk"},
    {"id": 9, "name": "Lobos/Cave 3 - -2 - Panuk"},
    {"id": 10, "name": "Lobos/Cave 3 - -3 - Panuk"},
    {"id": 11, "name": "Lobos/Cave 4 - -1 - Panuk"},
    {"id": 12, "name": "Lobos/Cave 4 - -2 - Panuk"},
    {"id": 13, "name": "Lobos/Cave 4 - -3 - Panuk"},
    {"id": 14, "name": "Dark Dragons - Direita - Panuk"},
    {"id": 15, "name": "Dark Dragons - Esquerda - Panuk"},
    {"id": 16, "name": "Dry Dragons - Direita - Panuk"},
    {"id": 17, "name": "Dry Dragons - Esquerda - Panuk"},
    {"id": 18, "name": "Tigres Superfice - Panuk"},
    {"id": 19, "name": "Tigres -2 - Panuk"},
    {"id": 20, "name": "Tigres -3 - Panuk"},
    {"id": 21, "name": "Grim Reapers - Caminho das Medusas - Panuk"},
    {"id": 22, "name": "Medusas - Direita - Panuk"},
    {"id": 23, "name": "Medusas - Esquerda - Panuk"},
    {"id": 24, "name": "Vampires - Direita - Panuk"},
    {"id": 25, "name": "Vampires - Esquerda - Panuk"},
    {"id": 26, "name": "Aboboras - Direita - Panuk"},
    {"id": 27, "name": "Aboboras - Esquerda - Panuk"},
    {"id": 28, "name": "Frost Hydras - Panuk"},
    {"id": 29, "name": "Turamak - Panuk"},
    {"id": 30, "name": "Lobos - Superfice 2 - Panuk"},
    {"id": 31, "name": "Lobos - Superfice 3 - Panuk"},
    {"id": 32, "name": "Lobos - Superfice 4 - Panuk"},
    {"id": 33, "name": "Dark Hydra Esquerda - Panuk"},
    {"id": 34, "name": "Dark Hydra Direita - Panuk"},
    {"id": 35, "name": "Banshee Direita - Panuk"},
    {"id": 36, "name": "Banshee Esquerda - Panuk"},
    {"id": 37, "name": "Ice Witch - Panuk"},
    {"id": 38, "name": "Abobora - Axel"},
    {"id": 39, "name": "Olhão - Axel"},
    {"id": 40, "name": "Witch - Axel"},
    {"id": 41, "name": "Earth Witch Esquerda - Axel"},
    {"id": 42, "name": "Earth Witch Direita - Axel"},
    {"id": 43, "name": "Vampire - Axel"},
    {"id": 44, "name": "Savage/Cave 150 - Axel"},
    {"id": 45, "name": "Medusa/Dark Hydra - Axel"},
    {"id": 46, "name": "Grim Reaper - Axel"},
    {"id": 47, "name": "Demon Estrela - Axel"},
    {"id": 48, "name": "Lobos Terreo - Tundra"},
    {"id": 49, "name": "Lobos -1 - Tundra"},
    {"id": 50, "name": "Lobos -2 - Tundra"},
    {"id": 51, "name": "Lobos -3 - Tundra"},
    {"id": 52, "name": "Demons - Tundra"},
    {"id": 53, "name": "Explores -1 - Tundra"},
    {"id": 54, "name": "Explores -2 - Tundra"},
    {"id": 55, "name": "Elf lord - Tundra"},
    {"id": 56, "name": "Cave 200 - Earth Witch Tundra"},
    {"id": 57, "name": "Cave 200 - Ice Witch"},
    {"id": 58, "name": "Cave 200 - Vicious spider"},
    {"id": 59, "name": "Cave 200 - Omothymus"},
    {"id": 60, "name": "Cave 200 - Orbweaver"},
    {"id": 61, "name": "Demons DP - Hellviwer"},
    {"id": 62, "name": "Muncher Sul - Hellviwer"},
    {"id": 63, "name": "Muncher Esquerda - Hellviwer"},
    {"id": 64, "name": "Muncher Norte Direita - Hellviwer"},
    {"id": 65, "name": "Livraria Fire - Hellviwer"},
    {"id": 66, "name": "Livraria Energy - Hellviwer"},
    {"id": 67, "name": "Livraria Death - Hellviwer"},
    {"id": 68, "name": "Livraria Ice - Hellviwer"},
    {"id": 69, "name": "Livraria Earth - Hellviwer"},
    {"id": 70, "name": "Slauter - Esquerda - Hellviwer"},
    {"id": 71, "name": "Slauter - Direita - Hellviwer"},
    {"id": 72, "name": "Behemoth - Hellviwer"},
    {"id": 73, "name": "Panther - Hellviwer"},
    {"id": 74, "name": "Rhinor - Hellviwer"},
    {"id": 75, "name": "Incerator - Hellviwer"},
    {"id": 76, "name": "The Judge Esquerda - Hellviwer"},
    {"id": 77, "name": "The Judge Direita - Hellviwer"},
    {"id": 78, "name": "Sand Djin - Hellviwer"},
    {"id": 79, "name": "Elf Lord - Umbra"},
    {"id": 80, "name": "Night Elf - Umbra"},
    {"id": 81, "name": "Medusa Terreo - Umbra"},
    {"id": 82, "name": "Medusa -1 - Umbra"},
    {"id": 83, "name": "Abobora - Umbra"},
    {"id": 84, "name": "Vampire - Umbra"},
    {"id": 85, "name": "Thunder Dragon - Umbra"},
    {"id": 86, "name": "Banshee - Terreo - Umbra"},
    {"id": 87, "name": "Banshee - -1 - Umbra"},
    {"id": 88, "name": "Dry Dragon - Umbra"},
    {"id": 89, "name": "Nomades Direita - Yakka"},
    {"id": 90, "name": "Nomades Esquerda - Yakka"},
    {"id": 91, "name": "Nomades Leader - Yakka"},
    {"id": 92, "name": "Giant Spider - Direita - Yakka"},
    {"id": 93, "name": "Vampire Aprentice/Ghost - Yakka"},
    {"id": 94, "name": "Dark Dragons - Yakka"},
    {"id": 95, "name": "Dragons/Dragons Lord - Yakka"},
    {"id": 96, "name": "Tumba Grim/Frost Hydras - Yakka"},
    {"id": 97, "name": "Giant Spider - Esquerda - Yakka"},
    {"id": 98, "name": "Thunder Dragon - Yakka"},
    {"id": 99, "name": "Banshee - Yakka"},
    {"id": 100, "name": "Frost Demon - Yakka"},
    {"id": 101, "name": "Vampire - Yakka"},
    {"id": 102, "name": "Dark Dragon - Esquerda - Yakka"},
    {"id": 103, "name": "Dark Dragon - Direita - Yakka"},
    {"id": 104, "name": "Tornado Grinders - Yakka"},
    {"id": 105, "name": "Vampire Apocolypses - Yakka"},
]
