name: Restart Bot Daily

on:
  schedule:
    - cron: '0 8 * * *'  # 4 AM RD es 8 AM UTC
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar hook de Render para reiniciar
        run: |
          curl -X POST https://api.render.com/deploy/srv-d01a9hbuibrs73ai9q3g?key=VZP4HCWRJRg