name: Restart Bot Daily

on:
  schedule:
    - cron: '0 8 * * *'  # 4 AM RD es 8 AM UTC
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout del código
        uses: actions/checkout@v2

      # Paso 2: Configurar Python (si no lo tienes aún)
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifica tu versión de Python

      # Paso 3: Instalar dependencias del sistema
      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1

      # Paso 4: Instalar dependencias de Python
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 5: Ejecutar script para borrar los mensajes de "ocupados"
      - name: Borrar mensajes ocupados
        run: |
          python borrar_ocupados.py  # Este es el script que te mencioné antes

      # Paso 6: Llamar al hook de Render para reiniciar
      - name: Llamar hook de Render para reiniciar
        run: |
          curl -X POST https://api.render.com/deploy/srv-d01a9hbuibrs73ai9q3g?key=VZP4HCWRJRg
