name: Reiniciar Bot

on:
  schedule:
    # Reiniciar cada día a las 4 AM (hora UTC)
    - cron: "0 4 * * *"

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Reiniciar el bot
      run: |
        echo "Reiniciando el bot..."
        python main.py
