name: Restart Bot

on:
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente desde GitHub UI

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restart Bot (via Render API)
        run: |
          curl -X POST https://api.render.com/deploy/srv-d01a9hbuibrs73ai9q3g?key=VZP4HCWRJRg
