name: Restart Bot Manually

on:
  workflow_dispatch:  # Esto permite que el workflow se ejecute manualmente desde la interfaz de GitHub

jobs:
  restart:
    runs-on: ubuntu-latest  # Esto indica que usaremos Ubuntu como sistema para el job

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2  # Descarga tu código del repositorio

      - name: Configurar Python
        uses: actions/setup-python@v2  # Configura Python en el runner de GitHub
        with:
          python-version: '3.x'  # Versión de Python (ajusta si es necesario)

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip  # Actualiza pip
          pip install -r requirements.txt  # Instala las dependencias del bot

      - name: Reiniciar el bot
        run: |
          python main.py  # Reinicia el bot
